export const endpoints = [
  ['POST', '/auth/register', 'Create customer, vendor or admin user'],
  ['POST', '/auth/login', 'Issue access token and refresh cookie'],
  ['POST', '/auth/refresh', 'Rotate access token'],
  ['POST', '/auth/forgot-password', 'Send password reset OTP'],
  ['GET', '/vendors', 'Search and filter verified vendors'],
  ['POST', '/vendors', 'Vendor/admin creates vendor profile'],
  ['PATCH', '/vendors/:id/approve', 'Admin approves vendor'],
  ['GET', '/events', 'List role-scoped events'],
  ['POST', '/events', 'Create event with budget and timeline'],
  ['POST', '/budgets', 'Create expense/budget line item'],
  ['POST', '/bookings', 'Send vendor booking request'],
  ['PATCH', '/bookings/:id/status', 'Vendor/admin accepts or rejects booking'],
  ['POST', '/guests', 'Add guest and QR token'],
  ['PATCH', '/guests/check-in/:token', 'QR guest check-in'],
  ['POST', '/payments/intent', 'Create Stripe payment intent'],
  ['POST', '/reviews', 'Publish customer vendor review'],
  ['POST', '/ai/recommendations', 'Generate OpenAI planning recommendations'],
]
